### ISSUE TITLE
아이폰 사파리 height: 100vh 문제

### ISSUE THREAD

**Issue by eunnbi** [eunnbi/dev#5]
**Solution**
자바스크립트와 css로 해결
```tsx
// pages/index.tsx
useEffect(() => {
    const vh = window.innerHeight * 0.01;
    console.log(vh);
    document.documentElement.style.setProperty("--vh", `${vh}px`);
}, []);

const Main = styled.main`
    height: calc(100vh - 60px);
    height: calc(var(--vh, 1vh) * 100 - 60px);
`;
```

```css
/* styles.global.css */

:root {
    --vh : 100%;
}

```
